### ISSUE TITLE
Remove login for `project down/delete`

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#102]
From #72 

>  But anyway, all destructive actions such as project down or ... delete should be executable without a valid login statis

- remove login from `unikube project down`
- remove login from `unikube project delete`

**Comment by vvvityaaa** [comment]
Current codebase does not require authentication for `unikube project down` and `unikube project delete`

**Comment by Schille** [comment]
I can confirm for `project down` that a login is not required.
