### ISSUE TITLE
Project down returns two projects, when only one is up

### ISSUE THREAD

**Issue by vvvityaaa** [unikubehq/cli#115]
Project down should not return a selection of projects to shut down, as it is only possible to up one project at a time.

**Comment by buschNT** [comment]
I am not sure why you get 2 projects anyway. Since it is only possible to have one project up, there should be only one suggestion for the down command. This is actually exactly the behavior I get. If I try to up a second project, I get an error.

Thus, the current logic should work.

**Comment by Schille** [comment]
I suppose we should not prompt a selector anyway.
