### ISSUE TITLE
Token refresh not working properly?

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#119]
I have the feeling that I am logged out too frequent.
Does anyone have the same feeling? Maybe the token refresh logic does not work properly.

**Comment by vvvityaaa** [comment]
I have the same feeling. I am getting logged out multiple times per day.

**Comment by SteinRobert** [comment]
Same. Happens to me too.

**Comment by buschNT** [comment]
I do not observe this issue anymore. @SteinRobert @vvvityaaa Do you still get logged several times per day???

**Comment by buschNT** [comment]
Seems to be solved, now.
