### ISSUE TITLE
New command: `unikube ps`

### ISSUE THREAD

**Issue by ViggieM** [unikubehq/cli#120]
maybe a useful and simple command would be to get the currently active project from the cli? Maybe the same output as `unikube project info`?

**Comment by buschNT** [comment]
`unikube project info` should always give you the current project info based on the context. There is no "active" project anymore.

**Comment by Schille** [comment]
What about the `up'ed` project?

**Comment by buschNT** [comment]
Do we want something like:
`unikube project up --list`
To see which project is up?

Or docker style:
`unikube ps`
`unikube project ps`

**Comment by Schille** [comment]
`unikube ps` is a nice idea.
It could list running clusters and also switch operations.

**Comment by SteinRobert** [comment]
I was just creating a new issue, then found this one. From the other issue:

> I was wondering if there is a case for some kind of `unikube status`.
> Things the command could do:
> - display the currently "upped" project(s)
> - the context (like `context show`)
> - login status
> - cli version (pending updates)
