### ISSUE TITLE
AutoReload while coding kills switched app

### ISSUE THREAD

**Issue by schwobaseggl** [unikubehq/cli#151]
When you are coding with a switched app and autor-reload enabled, having invalid code (even temporarily while typing) triggers a failed reload which stops/exits the switched container.

One then has to call `app switch` again which triggers a (possibly lengthy) image build.

Is there a way to make the switched app more robust in that it keeps trying to restart the switched container?

**Comment by Schille** [comment]
I'd say this is currently not in the scope of Unikube. 
We added the `--no-build` flag in order to skip the Docker build process in case you only changed code. At least, that will speed up the process of starting up a failed switch operation a little bit.
