### ISSUE TITLE
Project not available after creation

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#155]
After creating a new project on the platform it is not available in the CLI. Refreshing the login helps - I guess the login token does not contain the correct permission, only after refreshing.

Possible solution: All queries which imply permission checks should refresh the rpt before executing the query.

**Comment by Schille** [comment]
I find this important, especially when following the "Getting started" guide. Projects that are just created on the platform do not immediately appear in the CLI. This will lead to question marks.
