### ISSUE TITLE
`kill switch` when `deck install` is executed?

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#179]
I was wondering if it is actually causing problems when a `switch` command is active and `deck install` is executed. Seems to me as it should be killed (and maybe restarted after a successful installation).

**Comment by Schille** [comment]
It is quite easy to detect open switch operations: https://github.com/unikubehq/cli/blob/8de3b55de7017c5d09787c1237acaf5ced548d6a/src/local/system.py#L341
Easy fix: abort the `deck install` with a message as long as a switch is running.
