### ISSUE TITLE
Better handling of duplicated project titles

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#20]
The interactive project selector show projects which may have been deleted on the platform already since it draws only from existing local cluster information.
![image](https://user-images.githubusercontent.com/676722/120016304-bb414e00-bfe4-11eb-95bb-711031dfa0b0.png)
When a project gets created for the second time (or another project with the same title) the interactive selector is not working properly anymore since the `project_id` solely depends on matching the title.

Currently there is no way to select the correct/existing `buzzword-counter` project in my example. 

I'd suggest to select a project from a query result and match the cluster based on the selection.

**Comment by buschNT** [comment]
How shall we approach this issue? As far as I know, it is only possible to use a list as choices for `inquirer.List()`, which we use to generate these selection prompts. Thus we might have to include the ID or other information in the selection, e.g.:
- "buzzword-counter (1234-1234-1234-1234)"
- "buzzword-counter (5678-5678-5678-5768)"

Thus, after the user selected a value, we could extract the ID and select the correct project/deck/etc. based on the ID and not the title.

**Comment by Schille** [comment]
@buschNT I like that approach for now. We may find a more sophisticated solution in the future, however even the user needs a distinction in the list in order to select the correct item.

**Comment by SteinRobert** [comment]
@buschNT @Schille probably we should prohibit duplicate project titles within the same organization. Shouldn't be that hard to implement. I feel like the UUIDs do not really help users distinguishing the projects.

**Comment by buschNT** [comment]
@SteinRobert Yes, UUIDs might not be the best to distinguish projects. We can prohibit duplicate project names in the same organization, then we can resolve potential duplicates across organizations with the organization name:
- "buzzword-counter (Blueshoe)"
- "buzzword-counter (Redshoe)"

**Comment by buschNT** [comment]
I pushed my current code (branch "feature/#20-duplicate-project-title"). Currently, the `project info` has the new implementation. Thus it would have to be integrated into the other project commands. I don't have time next week. So if someone wants to continue, feel free.

**Comment by vvvityaaa** [comment]
@buschNT I have continued to integrate your implementation into new commands. Will also continue doing it next week.
