### ISSUE TITLE
setup.py entry_points syntax wrong

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#221]
From what I have seen the `entry_points` syntax in the setup.py file seems wrong.

Currently:
```python
    entry_points="""
        [console_scripts]
        unikube=unikube:cli
    """, 
```

Actual syntax seems to expect a dictionary:
```python
    entry_points = {
        'console_scripts': ['funniest-joke=funniest.command_line:main'],
    }
```

https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

**Comment by schwobaseggl** [comment]
@buschNT Seems to be working with config style string, too. But the proper python data structure is certainly nicer. Should also be easy pickings.
