### ISSUE TITLE
`unikube app shell` only uses default container

### ISSUE THREAD

**Issue by tschale** [unikubehq/cli#257]
Currently when using the shell command on a pod with multiple containers, the default container is chosen. We should support specifying a target container.

Example:
![image](https://user-images.githubusercontent.com/5681839/148803000-17ab8ac5-1fd3-4b03-a7be-beeafad31c20.png)
I would like to have a shell in `consentservice-admin` and not in `oauth2-proxy`.

**Comment by buschNT** [comment]
@tschale This should be solved by: https://github.com/unikubehq/cli/issues/230
Which CLI version are you using?

**Comment by tschale** [comment]
@buschNT I'm using 1.0.1. I've upgraded to 1.1.0, works like a charm. Thank you! :)
