### ISSUE TITLE
Project down command failing

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#27]
The `unikube project down` command currently fails with a GraphQL error.
At this location https://github.com/unikubehq/cli/blob/60ef3a6e8ebf31498c6f5f3d80d778eb0fa83a7b/src/context/context.py#L192-L204
I had 
```
organization_id=None project_id=None deck_id=None
```
which queries the platform with `id:None`. That is causing an error which prevents the `unikube project down` command from being effective.

**Comment by buschNT** [comment]
I cannot reproduce this error. The GraphQL error should be caught by the following function:

```python
    def __graph_ql(self, query: str, query_variables: dict) -> Union[dict, None]:
        # GraphQL
        try:
            graph_ql = GraphQL(authentication=self._auth)
            result = graph_ql.query(
                query,
                query_variables=query_variables,
            )
            key = next(iter(result))
            data = result[key]
        except Exception as e:
            data = None
            console.debug(e)
            console.exit_generic_error()

        return data
```

Thus I am not sure why the Graphgl error is visible.
