### ISSUE TITLE
ID as selection parameter + map organization/project/deck/app arguments to ID

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#30]
Map all organization/project/deck/app arguments to IDs in order to work with IDs only internally.

E.g. the argument:
`@click.argument("project_title", required=False)`
should be:
`@click.argument("project", required=False)`

It should be possible to enter:
- title
- slug
- ID

of a project and the CLI will convert the entered value into the corresponding ID if possible.

**Comment by Schille** [comment]
Can you confirm this working @vvvityaaa ?

**Comment by Schille** [comment]
This is working now.
