### ISSUE TITLE
better deck install console feedback

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#31]
The output of the `deck install` command is not very informative if the setting of a deck are wrong/missing.

Example (1st command with missing settings -> empty table):
![Screenshot from 2021-06-14 11-27-37](https://user-images.githubusercontent.com/6874607/121871385-55530700-cd04-11eb-986e-be0e7bf20201.png)

Maybe it is possible to print some more information from the Decks settings (e.g. Sops name)?

![Screenshot from 2021-06-14 11-35-28](https://user-images.githubusercontent.com/6874607/121871727-b8dd3480-cd04-11eb-9a3b-23ad9f389721.png)

**Comment by Schille** [comment]
I am with you that showing an empty table does not make much sense. We could instead show a message that there is no Ingress configuration available (which is an absolutely valid state).
Finding out that configuration is missing is a much more difficult challenge. Eventually, it could be good to not configure a `values path` when the charts simply do not require it. In most cases this will be a warning at least.
