### ISSUE TITLE
Setup for automated cli testing is missing

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#38]

**Comment by Schille** [comment]
Once we can run automated tests I can add a Coveralls reporting with QA on the coverage for PRs.

**Comment by buschNT** [comment]
Some example tests are in the "tests" folder. I am not exactly sure what is missing for the automated test setup. I created a PR #41 where I added the pytest to the workflow.

**Comment by Schille** [comment]
@vvvityaaa is currently adding more tests; with PR #41 merged tests are running automatically using GitHub Actions

**Comment by Schille** [comment]
I close it for now.
