### ISSUE TITLE
Typical `kubectl` commands missing

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#40]
In a recent version we had typical `kubectl` commands to introspect the cluster like:
- see all pods
- describe a pod
- get a `kubectl` config/context for advanced usage using `kubectl`

In addition, currently it is not possible to see the Ingress configuration again.

**Comment by Schille** [comment]
I know there are some already implemented. We should be able to transfer the `describe` and `env` functionality from the prototype CLI.

**Comment by buschNT** [comment]
I guess we would have to discuss this issue. How we really want all those advanced features? How should the commands look like?
Furthermore we have issue #9 and #13 . Are those the missing commands?
