### ISSUE TITLE
cli command: ingress

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#54]
A command to show the ingress path is missing. Currently its just shown once (I think after deck installation).

I guess, the best location would be under `unikube app ingress`.

**Comment by schwobaseggl** [comment]
@buschNT Isn't `unikube deck ingress` more to the point? After all, aren't ingresses defined at the deck level?

**Comment by buschNT** [comment]
It's fine for me. `deck` seems to be the right place.

**Comment by Schille** [comment]
Not sure tho. We defined `app` as an instantiated `deck`, hence the command belongs to the `app` command group (just as `shell`, `switch`, `env`, etc.). Otherwise we should be consistent with other commands too.

**Comment by Schille** [comment]
Closed with #79
