### ISSUE TITLE
Update available info message

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#58]
If there is a newer CLI version it would be nice to be informed when you execute a command.

Possible solutions:
- The version could be checked at login (unikube login) and a corresponding info text could then be displayed.
- Additionally this info text can also be added when running the unikube --version command

**Comment by Schille** [comment]
I'd say, check when:
- login
- `system verify`
- `--version`

**Comment by vvvityaaa** [comment]
maybe you have an idea of how to implement the same functionality for --version as it gets the version via setup file? Writing info message about availability of newer version to the VERSION file or to the version variable in setup.py seems like a not good idea

**Comment by SteinRobert** [comment]
Maybe you could customize the `message` of the version_option decorator?
https://click.palletsprojects.com/en/8.0.x/api/?highlight=version#click.version_option

**Comment by buschNT** [comment]
Yes, the current `--version` option is from click, thus I agree with Robert. I guess you have to modify the `@click.version_option()` behavior or we could write our own `--version` logic using a `@click.option("version", is_flag=True, ....)`. If that is possible.
