### ISSUE TITLE
Fetching manifests does not handle expired access tokens

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#62]
From time to time I see something like this when installing a deck: `[ERROR] Could not load manifest: 403 Client Error: Forbidden for url: [...]`. From what I see this seems to be related with an expired access token. Once I login again the `deck install` command is successful.

**Comment by Schille** [comment]
Can you confirm that working now @vvvityaaa ?

**Comment by vvvityaaa** [comment]
I cannot reproduce this error anymore
