### ISSUE TITLE
Success Message when project up fails

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#66]
After running `unikube project up` of a project the command fails, but finishes with a success message:

<img width="634" alt="Bildschirmfoto 2021-06-30 um 21 30 41" src="https://user-images.githubusercontent.com/1231105/124020350-772dd880-d9ea-11eb-86cb-2f6ca020ecf7.png">

€dit: The project appears in the project list / project delete command even though the cluster wasn't setup.

**Comment by Schille** [comment]
I can't reproduce this issue with the latest code. Could you please verify it still exists and add more information in what context (orga and project) that happens?
