### ISSUE TITLE
MacOS installation via Homebrew

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#75]
Not all OSX users do have Python installed or know about pip.
Brew is a far more known solution for installing cli tools. 

From what a read it's not that hard to create a formula to make the cli installable via `brew`.

Definitely something we should think about.

- [x] create homebrew formula repo
- [x] add installation description to readme
- [x] add installation description to documentation
- [x] automate homebrew formula update on cli release

Repo: https://github.com/unikubehq/homebrew-tooling

**Comment by tobifroe** [comment]
We could use [homebrew-pypi-poet](https://github.com/tdsmith/homebrew-pypi-poet) to generate the formula on release, [this action](https://github.com/dawidd6/action-homebrew-bump-formula) could be used to fork the brew repo/create a PR with the updated formula.
