### ISSUE TITLE
cli command: app -> list

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#8]
Not implemented: `unikube app list`

**Comment by buschNT** [comment]
@Schille How do we plan to get the app information, e.g. for this `app list` command. Do we have to extract it from the running cluster, or do we plan to have a "app service" which we can query via GraphQL (if that is actually possible)?

**Comment by Schille** [comment]
I wonder if this is actually `get pods` of a running cluster (if yes, I would name it just so)? What is `app list` for anyway?
