### ISSUE TITLE
ReadMe Test section

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#95]
@vvvityaaa Can you maybe add 2-3 sentence on how to get the tests running locally into the ReadMe file? I guess you have been working on them. I think I have to set some local ENV variables? I tried to add a ".env" file, but I couldn't get the tests running.

By the way: The test structure and content looks great :+1: Far better than before.

**Comment by buschNT** [comment]
@vvvityaaa thanks for the email/message. Maybe you can review #101

**Comment by Schille** [comment]
I merged. Found it appropriate. 
@buschNT will you close this issue, please?
